blog/app1/urls.py
from django.urls import path
from app1 import views
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', views.inicio, name = "inicio"),
    path('login/', views.login_request, name = "login"),
    path('registro/', views.register, name = "registro"),
    path('perfil/', views.editarPerfil, name = "perfil"),

    path('provincias/', views.provincias, name = "provincias"),
    path('opiniones/', views.opiniones, name = "opiniones"),
    path('obligatorio/', views.obligatorio, name = "obligatorio"),
    path('no_hay_pagina_aun/', views.no_hay_pagina_aun, name = "no_hay_pagina_aun"),

    path('about/', views.about, name = "about"),
    path('logout', LogoutView.as_view(template_name='app1/logout.html'), name= 'logout'),

    path('eliminarCuenta/', views.eliminarCuenta, name='eliminarCuenta'),
    path('cuentaEliminada/', views.delete_account, name='cuentaEliminada'),
    ]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/', include('app1.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/app1/models.py
from django.db import models
from django.contrib.auth.models import User

#Perfil de usuario
class UserProfile(models.Model):
    nickname = models.CharField(max_length=20, unique = True)
    first_name = models.CharField(max_length = 50)
    last_name = models.CharField(max_length = 50)
    email = models.EmailField(unique = True)
    password = models.CharField(max_length=20, default=123456)

    def __str__(self):
        return self.nickname

#Avatar del usuario  
class Avatar(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='avatares/', null=True, blank=True)
    
    def __str__(self):
        return f"{self.user} - {self.imagen}"

#Provincias
class Provincia(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    imagen = models.ImageField(upload_to='provincias/')

    def __str__(self):
        return self.nombre

#Comentario
class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    provincia = models.ForeignKey(Provincia, on_delete=models.CASCADE)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def str(self):
        return f"Comment by {self.user} on {self.provincia.nombre}"

class Opinion(models.Model):
    provincia = models.ForeignKey(Provincia, on_delete=models.CASCADE)
    lugar_turistico = models.CharField(max_length=100)
    comentario = models.TextField()

blog/app1/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from .models import *
#class RegistroFormulario(forms.Form):
    #nickname = forms.CharField()
    #first_name = forms.CharField()
    #last_name = forms.CharField()
    #email = forms.EmailField()
    #password = forms.CharField(widget=forms.PasswordInput, label='Contraseña')
    
class SignInForm(forms.Form):
    nickname = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
    
class UserRegisterForm(UserCreationForm):
    
    username = forms.CharField()
    email = forms.EmailField()
    password1 = forms.CharField(label='Contraseña', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repetir la contraseña', widget=forms.PasswordInput)
    first_name = forms.CharField()
    last_name = forms.CharField()
    
    class Meta:
        model = User
        fields = ['username','email', 'password1', 'password2', 'first_name', 'last_name']
        help_texts = {k:"" for k in fields}
        
class UserEditForm(forms.ModelForm):
    email = forms.EmailField(label="Modificar correo.")
    password1 = forms.CharField(label="Contraseña", widget=forms.PasswordInput, required=False)
    password2 = forms.CharField(label="Repetir la contraseña", widget=forms.PasswordInput, required=False)
    first_name = forms.CharField(label="Nombre")
    last_name = forms.CharField(label="Apellido")
    avatar_image = forms.ImageField(label="Subir imagen de avatar", required=False)

    class Meta:
        model = User
        fields = ['email', 'password1', 'password2', 'first_name', 'last_name', 'avatar_image']
        help_texts = {k: "" for k in fields}

class OpinionForm(forms.ModelForm):
    class Meta:
        model = Opinion
        fields = ['provincia', 'lugar_turistico', 'comentario']

blog/app1/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .forms import *
from .models import *
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate, get_user_model
from django.contrib.auth.decorators import login_required
#from django.http import HttpResponse

#Menú Principal
def inicio(request):
    #user_avatar = Avatar.objects.filter(user=request.user).first()
    #url = user_avatar.imagen.url if user_avatar else None
    return render(request, "app1/inicio.html")#, {"url": url})

#Provincias
@login_required
def provincias(request):
    return render(request, "app1/provincias.html")

#About
def about(request):
    return render(request, "app1/about.html")

def obligatorio(request):
    return render(request, "app1/obligatorio.html")

@login_required
def buenos_aires(request):
    return render(request, "app1/buenos_aires.html")

@login_required
def mendoza(request):
    return render(request, "app1/mendoza.html")

@login_required
def rio_negro(request):
    return render(request, "app1/rio_negro.html")

@login_required
def no_hay_pagina_aun(request):
    return render(request, "app1/no_hay_pagina_aun.html")

#Registro
def register(request):

    if request.method == 'POST':
        
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            
            username = form.cleaned_data['username']
            form.save()
            return render(request, "App1/inicio.html", {"mensaje": "Usuario Creado"})

    else:
        form = UserRegisterForm()

    return render(request, "app1/registro.html", {"form":form})

def login_request(request):
    
    if request.method == "POST":
        form = AuthenticationForm(request, data = request.POST)
        
        if form.is_valid():
            
            usuario = form.cleaned_data.get('username')
            contras = form.cleaned_data.get('password')
            
            user = authenticate(username=usuario, password=contras)
            
            if user is not None:
                login(request, user)
                
                return render(request, 'app1/inicio.html', {'mensaje': f"Bienvenido {usuario}"})
            else:
                return render(request, 'app1/inicio.html', {'mensaje': "Error: Usuario o contraseña incorrectos."})
        else:
                return render(request, 'app1/inicio.html', {'mensaje': "Error: Datos no válidos."})
    
    form = AuthenticationForm()
    
    return render(request, 'app1/login.html', {'form': form})


#Perfil
@login_required

def editarPerfil(request):
    usuario = request.user

    try:
        avatar_instance = Avatar.objects.get(user=usuario)
    except Avatar.DoesNotExist:
        avatar_instance = None

    if request.method == 'POST':
        miFormulario = UserEditForm(request.POST, request.FILES)
        if miFormulario.is_valid():
            informacion = miFormulario.cleaned_data

            usuario.email = informacion['email']
            usuario.last_name = informacion['last_name']
            usuario.first_name = informacion['first_name']
            usuario.save()

            password1 = informacion['password1']
            password2 = informacion['password2']

            if password1 and password2 and password1 == password2:
                usuario.set_password(password1)
                usuario.save()

            avatar_image = informacion['avatar_image']
            if avatar_image:
                # Update or create the avatar instance for the user
                if avatar_instance:
                    avatar_instance.imagen = avatar_image
                    avatar_instance.save()
                else:
                    avatar_instance = Avatar(user=usuario, imagen=avatar_image)
                    avatar_instance.save()

            return render(request, 'app1/inicio.html')  # Redirect to the user's profile page

    else:
        initial_data = {
            'email': usuario.email,
        }
        if avatar_instance:
            initial_data['avatar_image'] = avatar_instance.imagen
        miFormulario = UserEditForm(initial=initial_data)

    return render(request, 'app1/perfil.html', {"miFormulario": miFormulario, "usuario": usuario})

#Opiniones comentadas
@login_required
def opiniones(request):
    if request.method == 'POST':
        form = OpinionForm(request.POST)
        if form.is_valid():
            provincia_seleccionada = form.cleaned_data['provincia']
            lugar_turistico = form.cleaned_data['lugar_turistico']
            comentario = form.cleaned_data['comentario']
            
            # Crear y guardar la opinión en la base de datos
            opinion = Opinion(
                provincia=provincia_seleccionada,
                lugar_turistico=lugar_turistico,
                comentario=comentario
            )
            opinion.save()
            opinions = Opinion.objects.all()  # Fetch all opinions from the database
            return render(request, 'app1/opiniones.html', {'form': form, 'opinion': opinions})
    else:
        form = OpinionForm()
        opinions = Opinion.objects.all()  # Fetch all opinions from the database
        
    return render(request, 'app1/opiniones.html', {'form': form, 'opinion': opinions})


def isAdmin(User):
    return User.is_superuser

@login_required
def eliminarCuenta(request):
    return render(request, 'app1/eliminarCuenta.html')

@login_required
def delete_account(request):
    if request.method == 'POST':
        user = request.user
        user.delete()
        return render(request, 'app1/inicio.html')  # Redirect to an appropriate page after deletion

    return render(request, 'cuentaEliminada.html')

blog/app1/templates/app1/about.html
<!DOCTYPE html>
<html lang="en">
    <head>

        {% load static %}
        <style>
            .avatar-container {
        width: 100px;
        height: 100px;
        border-radius: 100%;
        overflow: hidden;
        }

        .avatar-image {
            width: 100%;
            height: 100%;
            object-fit: cover;
        }
        </style>
        
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Argentravel</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'app1/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">

                {% if request.user.is_authenticated %}
                {% if request.user.avatar_set.first %}
                    <div class="avatar-container">
                        <img src="{{ request.user.avatar_set.first.imagen.url }}" class="avatar-image" />
                    </div>
                {% endif %}
                <p class="text-muted small mb-4 mb-lg-0">{{ request.user.username }}</p>
                 {% endif %}

                <a class="navbar-brand" href="{% url 'inicio' %}">Inicio</a>
                <a class="navbar-brand" href="{% url 'provincias' %}">Provincias</a>
                <a class="navbar-brand" href="{% url 'opiniones' %}">Opiniones</a>

                {% if not request.user.is_authenticated %}
                    <a class="btn btn-primary" href="{% url 'registro' %}">Sign Up</a>
                    <a class="btn btn-primary" href="{% url 'login' %}">Log In</a>
                {% else %}
                    <a class="btn btn-primary" href="{% url 'perfil' %}">Perfil</a>
                    <a class="btn btn-primary" href="{% url 'logout' %}">Cerrar sesión</a>
                {% endif %}
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="text-center text-white">
                            <!-- Page heading-->
                            <h1 class="mb-5">¿Quienes somos?</h1>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Icons Grid-->
        <section class="features-icons bg-light text-center">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4">
                        <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
                            <h3></h3>
                            <p></p>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
                            <img class="img-fluid rounded-circle mb-3" src="https://turismo.org/wp-content/uploads/2010/10/Bandera-de-Argentina.png" alt="..." />
                            <h3>Argentravel</h3>
                            <p class="lead mb-0">Argentravel es una web destinada a brindar la mayor información posible al viajero que quiera visitar distintos lugares turisticos del país</br>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
                            <h3></h3>
                            <p></p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section class="features-icons bg-light text-center">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4">
                        <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
                            <img class="img-fluid rounded-circle mb-4" src="https://media.licdn.com/dms/image/D4D03AQFkp8cwfNLimA/profile-displayphoto-shrink_800_800/0/1671835896606?e=1696464000&v=beta&t=LITP4QJqwHNpaJ1gcyihhIwZphTlnX985qnq8iV1lDU" alt="..." />
                            <h3>Leandro R. Dramis</h3>
                            <p class="lead mb-0">¡Estudiante de Python en Coder House!<br>Co-fundador de la web y autor del proyecto</br>
                            </p>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
                            <h3></h3>
                            <p class="lead mb-0"></p>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
                            <img class="img-fluid rounded-circle mb-3" src="https://media.licdn.com/dms/image/D4D35AQHq45m_Zd9-iA/profile-framedphoto-shrink_800_800/0/1688147949005?e=1691794800&v=beta&t=wIV2dA0FXkBtRFVdquXxNmek5lMASk1k7f7YfdeeDbY" alt="..." />
                            
                            <h3>Juan Pablo Apecetche</h3>
                            <p class="lead mb-0">¡Estudiante de Python en Coder House!<br>Co-fundador de la web y autor del proyecto</br>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        {% block contenidoQueCambia %}

        {% endblock %}

        <!-- Footer-->
        <footer class="footer bg-light">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                        <ul class="list-inline mb-2">
                            <li class="list-inline-item"><a href="{% url 'about' %}">About</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="{% url 'no_hay_pagina_aun' %}">Contact</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="{% url 'no_hay_pagina_aun' %}">Terms of Use</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="{% url 'no_hay_pagina_aun' %}">Privacy Policy</a></li>
                        </ul>
                        <p class="text-muted small mb-4 mb-lg-0">&copy; Your Website 2023. All Rights Reserved.</p>
                    </div>
                    <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                        <ul class="list-inline mb-0">
                            <li class="list-inline-item me-4">
                                <a href="{% url 'no_hay_pagina_aun' %}"><i class="bi-facebook fs-3"></i></a>
                            </li>
                            <li class="list-inline-item me-4">
                                <a href="{% url 'no_hay_pagina_aun' %}"><i class="bi-twitter fs-3"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="{% url 'no_hay_pagina_aun' %}"><i class="bi-instagram fs-3"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

blog/app1/templates/app1/buenos_aires.html
{% extends "app1/padre_lugares.html" %}
{% load static %}
{% block contenidoQueCambia %}

<header class="masthead">
    <div class="container position-relative">
        <div class="row justify-content-center">
            <div class="col-xl-6">
                <div class="text-center text-white">
                    <!-- Page heading-->
                    <h1 class="mb-5">¡Bienvenido a Buenos Aires!</h1>
                    </form>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Testimonials-->
<section class="testimonials text-center bg-light">
    <div class="container">
        <h2 class="mb-5">Recomendaciones para viajar</h2>
        <div class="row">
            {% for comment in comments %}
            <div class="col-lg-4">
                <div class="testimonial-item mx-auto mb-5 mb-lg-0">
                    <img class="img-fluid rounded-circle mb-3" src="{{ comment.user_image.url }}" alt="{{ comment.author }} Profile Image">
                    <h5>{{ comment.author }}</h5>
                    <p class="font-weight-light mb-0">{{ comment.content }}</p> #en views esta la def para la caja de comentarios
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

blog/app1/templates/app1/inicio.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <style>
            .avatar-container {
        width: 100px;
        height: 100px;
        border-radius: 100%;
        overflow: hidden;
        }

        .avatar-image {
            width: 100%;
            height: 100%;
            object-fit: cover;
        }
        </style>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Argentravel</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'app1/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">

                {% if request.user.is_authenticated %}
                {% if request.user.avatar_set.first %}
                    <div class="avatar-container">
                        <!-- Make sure to define appropriate CSS styles for the avatar -->
                        <img src="{{ request.user.avatar_set.first.imagen.url }}" class="avatar-image" alt="{{ request.user.username }} Avatar" />
                    </div>
                {% endif %}
                <p class="text-muted small mb-4 mb-lg-0">{{ request.user.username }}</p>
            {% endif %}
            
            
            
                <a class="navbar-brand" href="{% url 'inicio' %}">Inicio</a>
                <a class="navbar-brand" href="{% url 'provincias' %}">Provincias</a>
                <a class="navbar-brand" href="{% url 'opiniones' %}">Opiniones</a>

                {% if not request.user.is_authenticated %}
                    <a class="btn btn-primary" href="{% url 'registro' %}">Sign Up</a>
                    <a class="btn btn-primary" href="{% url 'login' %}">Log In</a>
                {% else %}
                    <a class="btn btn-primary" href="{% url 'perfil' %}">Perfil</a>
                    <a class="btn btn-primary" href="{% url 'logout' %}">Cerrar sesión</a>
                {% endif %}
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="text-center text-white">
                            <!-- Page heading-->
                            <h1 class="mb-5">¡Bienvenido a Argentina!</h1>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </header>

        {{mensaje}}

        <!-- Icons Grid-->
        <section class="features-icons bg-light text-center">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4">
                        <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
                            <img class="img-fluid rounded-circle mb-3" src="https://upload.wikimedia.org/wikipedia/commons/9/94/Stensj%C3%B6lejon_i_Mar_del_Plata.jpg" alt="..." />
                            <h3>Mar del Plata</h3>
                            <p class="lead mb-0">¡Conoce la ciudad del mar en Buenos Aires!</p>
                            <a href="{% url 'opiniones' %}">+Info</a><br></br>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
                            <img class="img-fluid rounded-circle mb-3" src="https://www.cronista.com/files/image/463/463673/62976e94a2645.jpg" alt="..." />
                            <h3>Bariloche</h3>
                            <p class="lead mb-0">¿Te gusta la nieve? Te esperamos en Bariloche</p>
                            <a href="{% url 'opiniones' %}">+Info</a><br></br>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="features-icons-item mx-auto mb-0 mb-lg-3">
                            <img class="img-fluid rounded-circle mb-3" src="https://media.tacdn.com/media/attractions-splice-spp-674x446/07/20/a5/f9.jpg" alt="..." />
                            <h3>Perdriel</h3>
                            <p class="lead mb-0">Conoce los viñedos de Mendoza y degusta un Malbec</p>
                            <a href="{% url 'opiniones' %}">+Info</a><br></br>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Testimonials-->
        <section class="testimonials text-center bg-light">
            <div class="container">
                <h2 class="mb-5">Opiniones</h2>
                <div class="row">
                    <div class="col-lg-4">
                        <div class="testimonial-item mx-auto mb-5 mb-lg-0">
                            <img class="img-fluid rounded-circle mb-3" src="https://us.123rf.com/450wm/massonforstock/massonforstock1904/massonforstock190400205/120423949-mujer-joven-fot%C3%B3grafo-profesional-con-c%C3%A1mara-en-el-antiguo-castillo-concepto-de-viajero.jpg?ver=6" alt="..." />
                            <h5>Graciela</h5>
                            <p class="font-weight-light mb-0">"¡Conocer la nieve en Bariloche fue mágico!"</p>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="testimonial-item mx-auto mb-5 mb-lg-0">
                            <img class="img-fluid rounded-circle mb-3" src="https://peru21.pe/resizer/EX8dpGeoJXZDKfZK8Oa53X5RnCw=/1200x1200/smart/filters:format(jpeg):quality(75)/cloudfront-us-east-1.images.arcpublishing.com/elcomercio/YYIW3AZD6VCWDOUFMOQJ5EVN6E.jpg" alt="..." />
                            <h5>Guillermo</h5>
                            <p class="font-weight-light mb-0">"Gracias a este blog conocí el mejor bar del mundo en Mendoza"</p>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="testimonial-item mx-auto mb-5 mb-lg-0">
                            <img class="img-fluid rounded-circle mb-3" src="https://us.123rf.com/450wm/serezniy/serezniy2303/serezniy230305770/199568700-turista-masculino-tomando-fotos-en-las-calles-de-la-ciudad.jpg?ver=6" alt="..." />
                            <h5>Damian</h5>
                            <p class="font-weight-light mb-0">"Excelente el casino de Mar del Plata! Las mesas que recomendaron fueron buenisimas!"</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- Footer-->
        <footer class="footer bg-light">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                        <ul class="list-inline mb-2">
                            <li class="list-inline-item"><a href="{% url 'about' %}">About</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="{% url 'no_hay_pagina_aun' %}">Contact</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="{% url 'no_hay_pagina_aun' %}">Terms of Use</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="{% url 'no_hay_pagina_aun' %}">Privacy Policy</a></li>
                        </ul>
                        <p class="text-muted small mb-4 mb-lg-0">&copy; Your Website 2023. All Rights Reserved.</p>
                    </div>
                    <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                        <ul class="list-inline mb-0">
                            <li class="list-inline-item me-4">
                                <a href="{% url 'no_hay_pagina_aun' %}"><i class="bi-facebook fs-3"></i></a>
                            </li>
                            <li class="list-inline-item me-4">
                                <a href="{% url 'no_hay_pagina_aun' %}"><i class="bi-twitter fs-3"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="{% url 'no_hay_pagina_aun' %}"><i class="bi-instagram fs-3"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>